// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {aliyunpan} from '../models';

export function CreatInstance(arg1:types.CreatInstanceReq):Promise<aliyunpan.UserInfo>;

export function GenerateQrcode():Promise<types.GenerateQrcodeResp>;

export function QrcodeState(arg1:types.QrcodeStateReq):Promise<types.QrcodeStateResp>;
