// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreatInstance(arg1) {
  return window['go']['backend']['App']['CreatInstance'](arg1);
}

export function CreateFolderByFramework(arg1) {
  return window['go']['backend']['App']['CreateFolderByFramework'](arg1);
}

export function DomReady(arg1) {
  return window['go']['backend']['App']['DomReady'](arg1);
}

export function GenerateQrcode() {
  return window['go']['backend']['App']['GenerateQrcode']();
}

export function GetCollectionDirectoryFolders() {
  return window['go']['backend']['App']['GetCollectionDirectoryFolders']();
}

export function GetCollectionDirectoryFramework() {
  return window['go']['backend']['App']['GetCollectionDirectoryFramework']();
}

export function GetDirectoryFrameworkByPath(arg1) {
  return window['go']['backend']['App']['GetDirectoryFrameworkByPath'](arg1);
}

export function Init() {
  return window['go']['backend']['App']['Init']();
}

export function QrcodeState(arg1) {
  return window['go']['backend']['App']['QrcodeState'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}
