// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {aliyunpan} from '../models';
import {context} from '../models';
import {directory} from '../models';

export function CreatInstance(arg1:types.CreatInstanceReq):Promise<aliyunpan.UserInfo>;

export function DomReady(arg1:context.Context):Promise<void>;

export function GenerateQrcode():Promise<types.GenerateQrcodeResp>;

export function GetCollectionDirectoryFolders():Promise<directory.DirectoryStructure>;

export function GetCollectionDirectoryFramework():Promise<directory.DirectoryStructure>;

export function Init():Promise<void>;

export function QrcodeState(arg1:types.QrcodeStateReq):Promise<types.QrcodeStateResp>;

export function Shutdown(arg1:context.Context):Promise<void>;
