// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateQrcode() {
  return window['go']['backend']['App']['GenerateQrcode']();
}

export function QrcodeState(arg1) {
  return window['go']['backend']['App']['QrcodeState'](arg1);
}
